interface JoyStickControllerConstants
{
   final int JOYSTICKCONTROLLER_BAUDRATE = 250000;
   final int JOYSTICKCONTROLLER_RIGHTBUTTON = 3;
   final int JOYSTICKCONTROLLER_UPBUTTON = 4;
   final int JOYSTICKCONTROLLER_DOWNBUTTON = 5;
   final int JOYSTICKCONTROLLER_LEFTBUTTON = 6;
   final int JOYSTICKCONTROLLER_STICKX = 0;
   final int JOYSTICKCONTROLLER_STICKY = 1;
   final int JOYSTICKCONTROLLER_STICKBUTTON = 2;
   final char JOYSTICKCONTROLLER_DELIMITER = ',';
}